# Model arguments
model_name_or_path: bczhou/tiny-llava-v1-hf
ref_model_name_or_path: llava-hf/llava-1.5-7b-hf
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# LoRA arguments
use_peft: true
lora_r: 16
lora_alpha: 128
lora_dropout: 0.05
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj
- gate_proj
- up_proj
- down_proj
- fc1
- fc2
- out_proj
- linear_1
- linear_2

dataset_mixer:
  ${YOUR_DATASET}: 1.0
dataset_splits:
- train
- test
preprocessing_num_workers: 1

# SFTTrainer arugments
bf16: true
do_eval: true
eval_strategy: epoch
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
learning_rate: 2.0e-05
log_level: info
logging_steps: 100 
logging_strategy: steps
lr_scheduler_type: cosine
# max_seq_length: 1024
max_steps: -1
num_train_epochs: 1
output_dir: outputs/vlm/dv2
overwrite_output_dir: true
per_device_train_batch_size: 16
per_device_eval_batch_size: 2
push_to_hub: false
remove_unused_columns: true
save_strategy: "steps"
save_steps: 100000000
save_total_limit: 1
seed: 42
warmup_ratio: 0.1
loss_type: distillm_v2